language: python
python:
  - '3.6'
script:
  - pip3 install -r requirements.txt
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    application: "AwsCodeDeloyApp"
    deployment_group: "AwsCodeDeloyGroup"
    region: "us-east-1"

