version: 0.0
os: linux
files:
  - source: /
    destination: /home/code
hooks:
   AfterInstall:
    - location: /home/code/scripts/installpython.sh
      runas: root
    - location: /home/code/scripts/runapp.sh
      runas: root
