version: 0.0
os: linux
files:
  - source: /
    destination: /home/code
hooks:
  BeforeInstall:
    - location: scripts/installpython.sh
      runas: root
  AfterInstall:
    - location: scripts/runapp.sh
      runas: root

